apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whoami.name" . }}
  labels: {{- include "whoami.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "whoami.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "whoami.labels" . | nindent 8 }}
    spec:
      containers:
        - name: whoami
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 80
