apiVersion: v1
kind: Service
metadata:
  name: {{ include "whoami.name" . }}
  labels: {{- include "whoami.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
  selector: {{- include "whoami.labels" . | nindent 4 }}